"""Initial Vespa schemas for glossator: one ``docs_*`` schema per index variant.

This replaces the migration the starter template generated rather than adding a
second one on top of it. That is allowed exactly once and only here: the
generated migration was never deployed to any environment, so no stored data and
no running schema depend on it, and there is nothing for a follow-up migration to
be compatible with.

Immutability: do not edit this file once deployed. Every migration is re-executed
at runtime by ``load_app_definition`` to recover the schema in memory, so editing
an applied migration changes both the deployed schema and the field map the
running process believes in. Add ``00X_*.py`` migrations for schema changes.

What the schemas add on top of the toolkit's chunk defaults: the chunk metadata
our chunker stamps (url, anchor, heading path, page title, kind, locale, section
index) is declared as root fields, which is what makes it filterable and rankable
instead of only stored -- the write path promotes a chunk-metadata key into a
same-named root field automatically.
"""

from mistralai.search.toolkit.plugins.vespa.app.schemas.app import (
    FieldDefinition,
    IndexingMode,
    SearchMode,
    VespaFieldDefinition,
)
from mistralai.search.toolkit.plugins.vespa.migration import (
    VespaMigration,
    create_schema,
    set_app_name,
    set_default_ranking_weights,
)

from glossator.index.variants import VARIANTS

# Vespa application name. Constrained to ``^[a-z]+$`` by the toolkit.
_APP_NAME = "glossator"


def _chunk_metadata_fields() -> list[VespaFieldDefinition]:
    """Root fields for the citation metadata every chunk carries.

    The toolkit's DOCUMENT_PER_CHUNK defaults (id, content, content_embedding,
    offsets, opaque metadata blob) are injected by ``create_schema``; these are
    the ones glossator needs indexed rather than merely stored.
    """
    return [
        # Citation target. An attribute so a query can filter or group by page;
        # fast-search because "everything from this page" is a common lookup.
        FieldDefinition.StringField(name="url", fast_search=True),
        # Deep-link fragment within the page. Never matched, only carried.
        FieldDefinition.StringField(name="anchor"),
        # Matched: a question often repeats the page's own title.
        FieldDefinition.TextField(name="page_title"),
        # Matched, BM25-enabled, multi-valued so the heading list round-trips as
        # a list rather than being flattened into one string. array<string>
        # yields elementwise BM25 (bm25_heading_path_max / _avg).
        FieldDefinition.TextField(name="heading_path", multi_dimensional=True),
        # Filters: doc | api | model (D-005, D-006) and the page's locale (D-008).
        FieldDefinition.StringField(name="kind", fast_search=True),
        FieldDefinition.StringField(name="locale", fast_search=True),
        # Position of the chunk's section in the page, for reading order.
        FieldDefinition.IntField(name="section_index"),
    ]


# Default weights for the generated two-phase rank profile (``weighted-rank2``).
# Baked into the rank profile's ``inputs`` and into each schema's generated
# default query profile, so they apply on the query-builder path too; a request
# may still override any of them via ``VespaSearchQuery.ranking_weights``.
#
# Phase 1 selects candidates cheaply (keep_rank_count 10000 per node); phase 2
# reranks the survivors (rerank_count 100 per node) with the expensive features.
_RANKING_WEIGHTS: dict[str, float] = {
    # -- phase 1: candidate selection ------------------------------------------
    # Lexical relevance of the chunk body. Unbounded, typically a few units.
    "bm25_content": 0.5,
    # Vector relevance in phase 1. closeness() reuses the distance the
    # nearestNeighbor operator already computed, so it is cheap enough here, and
    # it is 0 for a document the ANN clause did not match. Left at 0 -- the
    # starter's setting -- phase 1 is BM25-only and a purely semantic hit scores
    # 0 before reranking (D-012). Weighted at 5.0 so an ANN hit (closeness in
    # (0, 1]) is worth roughly as much as a strong BM25 match.
    "content_embedding_closeness": 5.0,
    # A question often names the page ("function calling") or the section path.
    "bm25_page_title": 0.3,
    # Multi-valued field: _max scores the best-matching heading in the path.
    "bm25_heading_path_max": 0.3,
    # -- phase 2: rerank --------------------------------------------------------
    # fieldMatch() over the body: position and proximity aware, too expensive
    # for phase 1.
    "match_content": 0.5,
    # Exact cosine similarity, recomputed rather than read off the ANN index.
    "content_embedding_cosine_similarity_score": 5.0,
}


class CreateIndexSchemaMigration(VespaMigration):
    """Create one chunk-level schema per index variant."""

    def migrate(self) -> None:
        set_app_name(_APP_NAME)
        for variant in VARIANTS.values():
            create_schema(
                name=variant.schema_name,
                mode=SearchMode.INDEX,
                indexing_mode=IndexingMode.DOCUMENT_PER_CHUNK,
                # The model, not a bare dimension count: embedding_dimensions is
                # deprecated and records the model as "unknown", which loses the
                # only fact that ties a schema to the embedder that may write to it.
                embedding_model=variant.embedding,
                fields=_chunk_metadata_fields(),
            )
            set_default_ranking_weights(variant.schema_name, _RANKING_WEIGHTS)
